SYNTAX_GENERATION_PROMPT = (
    "You are a strict Mermaid syntax generator. Produce one valid {diagram_type} diagram in pure Mermaid code. "
    "Output ONLY Mermaid syntax - no markdown fences, no 'mermaid' tag, no commentary.\n\n"
    "User description: {description}\n\n"
    "Authoring rules:\n"
    "- Start with the correct diagram keyword (flowchart TD|LR; sequenceDiagram; classDiagram; stateDiagram-v2; erDiagram; requirementDiagram; graph TD|LR).\n"
    "- Node/participant IDs use letters, numbers, or underscores only; labels may have spaces. Declare every participant/node before linking.\n"
    "- Keep edges directional and explicit; ensure each reference exists and arrow syntax is valid.\n"
    "- Prefer concise labels; avoid paragraphs inside nodes.\n"
    "- Styling rules:\n"
    "  * ONLY apply classDef and class assignments when the diagram type is one of: flowchart, stateDiagram, stateDiagram-v2, erDiagram, requirementDiagram.\n"
    "  * When allowed, define a small, readable palette (e.g., classDef default fill:#0d1117,stroke:#2563eb,color:#e5e7eb,stroke-width:2px; "
    "classDef accent fill:#f5f5f5,stroke:#10b981,color:#111827,stroke-width:2px;), and apply classes consistently to related nodes.\n"
    "  * When NOT allowed (e.g., sequenceDiagram, gantt, pie, journey, timeline, gitGraph, mindmap), DO NOT emit classDef, class, or node-level styling.\n"
    "  * When assigning a class to multiple nodes, separate node names with commas (e.g., class A,B,C accent).\n"
    "  * In classDef, prefer fill and stroke (or stroke-width) for colors; avoid relying on color: alone.\n"
    "- Use subgraphs/grouping only when it clarifies structure; keep indentation consistent.\n"
    "- Double-check punctuation (semicolons where needed), brace/indent structure, and participant/class/state declarations before returning.\n"
    "Return only the final Mermaid syntax with no wrappers."
)

ERROR_FIXING_PROMPT = (
    "You are a Mermaid syntax debugger. The code below failed to render; repair it and return only raw Mermaid syntax (no fences, no 'mermaid' tag).\n\n"
    "Original syntax:\n"
    "{syntax}\n\n"
    "Renderer error:\n"
    "{error_message}\n\n"
    "Correction rules:\n"
    "- Preserve the intended diagram type and structure; do not change content unnecessarily.\n"
    "- Ensure the opening line matches the diagram type (flowchart TD|LR, sequenceDiagram, classDiagram, stateDiagram-v2, graph TD|LR).\n"
    "- Validate IDs (letters/numbers/underscores only), declare missing participants/nodes, and fix malformed arrows or relationships.\n"
    "- Repair common syntax issues: unmatched brackets, missing semicolons/line breaks, mis-indented subgraphs, and broken class/style definitions.\n"
    "- Remove any markdown wrappers or stray commentary.\n"
    "Return only the corrected Mermaid syntax."
)
